### ISSUE TITLE
porting to windows

### ISSUE THREAD

**Issue by K3nn3th2** [pts/megapubdl#1]
hey there!

it is mentioned in the readme that porting to windows is possible.
can you give any advice how to achieve this? 
im currently recieving this error on my windows machine:

>     megapubdl.check_aes_128_ctr()
>   File "path\to\megapubdl.py", line 411, in check_aes_128_ctr
>     data = ''.join(yield_aes_ctr('foo\n', '\0' * 16))
>   File "path\to\megapubdl.py", line 368, in yield_aes_ctr
>     rfds, wfds, _ = select.select((rfd,), (wfd,), (), None)
> select.error: (10038, 'An operation was attempted on something that is not a socket')

any help would be great.

thanks for this awesome module!

**Comment by pts** [comment]
The easiest way to fix this error on Windows is installing PyCrypto.

If you don't want to install PyCrypto, then the call to `select.select` (as you reported above) in `yield_aes_ctr` needs to be fixed. Unfortunately `select.selct` on Windows supports only sockets, so `select.select` can't be used. One possible workaround is redirecting the output of `subprocess.Popen` to a temporary file, and then yielding bytes from that file. By doing a larger refactoring it would be possible to avoid the temporary file, and save the output to the final download output file instead.

**Comment by pts** [comment]
I'm closing this issue, because it's unlikely that I'm going to work on avoiding `select.select` in the near future. Volunteers are encouraged to send pull requests though, and then I'll reopen this issue.

**Comment by K3nn3th2** [comment]
thanks for the tip! it worked with PyCrypto.
